### ISSUE TITLE
Regression: std::optional<std::variant<>> nolonger works with GCC16 with C++26

### ISSUE THREAD

**Issue by kncos** [stephenberry/glaze#2353]
```c++
#include <glaze/glaze.hpp>
#include <bits/stdc++.h>

struct glaze_test {
  std::optional<std::variant<std::string, int>> a;
};

int main() {
  std::string json = R"(
  {
    "a": 1
  }
  )";

  auto result = glz::read_json<glaze_test>(json);
  if (!result) {
    std::cout << "no result" << result.error() << std::endl;
    return -1;
  }
  auto unwrap_optional = result.value().a;
  if (!unwrap_optional.has_value()) {
    std::cout << "null value" << std::endl;
    return 0;
  }

  auto variant = result.value().a.value();
  if (std::holds_alternative<std::string>(variant)) {
    std::cout << "variant string: " << std::get<std::string>(variant) << std::endl;
  } else if (std::holds_alternative<int>(variant)) {
    std::cout << "variant int: " << std::get<int>(variant) << std::endl;
  }
  return 0;
}
```

This program compiles fine with GCC 15.2.1, but not on GCC 16.0.1 with these flags:
```
g++ -std=c++26 main.cpp -o main
```

The specific error yielded in GCC 16.0.1 is:
```
sh-5.3# g++ -std=c++26 main.cpp -o main
In file included from /usr/include/glaze/json/json_ptr.hpp:11,
                 from /usr/include/glaze/core/ptr.hpp:9,
                 from /usr/include/glaze/beve/ptr.hpp:8,
                 from /usr/include/glaze/beve.hpp:8,
                 from /usr/include/glaze/glaze.hpp:36,
                 from main.cpp:2:
/usr/include/glaze/json/read.hpp: In instantiation of 'void glz::decode_index(Value&&, auto:606&&, auto:607&&, auto:608&&, SelectedIndex&& ...) [with auto Opts = opts{10, true, false, true, true, false, false, false, false, 32}; T = glaze_test; long unsigned int I = 0; Value = glaze_test&; SelectedIndex = {}; auto:606 = context&; auto:607 = const char*&; auto:608 = const char*&]':
/usr/include/glaze/json/read.hpp:357:34:   required from 'constexpr void glz::parse_and_invoke(Value&&, auto:612&&, auto:613&&, auto:614&&, SelectedIndex&& ...) [with auto Opts = opts{10, true, false, true, true, false, false, false, false, 32}; T = glaze_test; Value = glaze_test&; SelectedIndex = {}; auto:612 = context&; auto:613 = const char*&; auto:614 = const char*&]'
  357 |          decode_index<Opts, T, 0>(value, ctx, it, end, selected_index...);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glaze/json/read.hpp:3182:47:   required from 'static void glz::from<10, T>::op(auto:716&&, auto:717&&, auto:718&&, auto:719) [with auto Options = glz::opts{10, true, false, true, true, false, false, false, false, 32}; string_literal<...auto...> tag = glz::string_literal<1>{""}; auto:716 = glaze_test&; auto:717 = glz::context&; auto:718 = const char*&; auto:719 = const char*; T = glaze_test]'
 3182 |                      parse_and_invoke<Opts, T>(value, ctx, it, end);
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/include/glaze/json/read.hpp:60:45:   required from 'static void glz::parse<10>::op(T&&, Ctx&&, It0&&, It1) [with auto Opts = glz::opts{10, true, false, true, true, false, false, false, false, 32}; T = glaze_test&; Ctx = glz::context&; It0 = const char*&; It1 = const char*]'
   60 |             from<JSON, V>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx), std::forward<It0>(it),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   61 |                                              end);
      |                                              ~~~~
/usr/include/glaze/core/read.hpp:64:63:   required from 'glz::error_ctx glz::read(T&, auto:219&&, auto:220&&) [with auto Opts = opts{10, true, false, true, true, false, false, false, false, 0}; T = glaze_test; auto:219 = std::__cxx11::basic_string<char>&; auto:220 = context&]'
   64 |          parse<Opts.format>::template op<is_padded_on<Opts>()>(value, ctx, it, end);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/include/glaze/json/read.hpp:4792:40:   required from 'glz::expected<T, glz::error_ctx> glz::read_json(Buffer&&) [with T = glaze_test; Buffer = std::__cxx11::basic_string<char>&; expected<T, error_ctx> = std::expected<glaze_test, error_ctx>]'
 4792 |       const error_ctx ec = read<opts{}>(value, std::forward<Buffer>(buffer), ctx);
      |                            ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:26:43:   required from here
   26 |   auto result = glz::read_json<glaze_test>(json);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/glaze/json/read.hpp:306:83: error: ambiguous template instantiation for 'struct glz::from<10, std::optional<std::variant<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >'
  306 |                from<JSON, std::remove_cvref_t<V>>::template op<ws_handled<Opts>()>(
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  307 |                   get_member(value, get<I>(to_tie(value))), ctx, it, end);
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
/usr/include/glaze/json/read.hpp:2075:11: note: candidates are: 'template<class T>  requires (readable_array_t<T>) && !(emplace_backable<T>) && !(resizable<T>) && (emplaceable<T>) struct glz::from<10, T> [with T = std::optional<std::variant<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >]'
 2075 |    struct from<JSON, T>
      |           ^~~~~~~~~~~~~
/usr/include/glaze/json/read.hpp:4440:11: note:                 'template<class T>  requires ((nullable_t<T>) || (nullable_value_t<T>)) && !(is_expected<T>) && !(is_array_v<T>) && !(custom_read<T>) struct glz::from<10, T> [with T = std::optional<std::variant<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >]'
 4440 |    struct from<JSON, T>
      |           ^~~~~~~~~~~~~
/usr/include/glaze/json/read.hpp:306:83: error: incomplete type 'glz::from<10, std::optional<std::variant<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >' used in nested name specifier
  306 |                from<JSON, std::remove_cvref_t<V>>::template op<ws_handled<Opts>()>(
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  307 |                   get_member(value, get<I>(to_tie(value))), ctx, it, end);
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
```

Note: I have GCC 15.2.1 running on an arch machine (btw) and GCC 16.0.1 running in a `fedora:44` container

Note: It DOES compile on GCC 16.0.1 with the flag `-std=c++23`, and the project's readme says that Glaze requires c++23. However, given that you have several issues open where you're experimenting with c++26 stuff such as #1586 and i think most would interpret "requires c++23" to mean "at least c++23", i thought it was worth bringing up

Note: I used Glaze v7.1.0 for this demonstration, and also tried it out `1ed0998` (head of main as of writing this), and had the same issue in both situations. On arch with GCC 15.2.1 i'm using v7.1.0

**Comment by stephenberry** [comment]
Ah, in C++26 std::optional gets range support, which current confuses Glaze's concept checking. Thanks for reporting! Will fix this.

**Comment by stephenberry** [comment]
I just merged in a major #2217 PR that brings C++26 reflection into Glaze. This branch had fixed your bug already. I'll keep this on `main` a few days in case there are any significant compilation issues to work through.
