### PR TITLE
Boost.Asio compatibility

### LINKED ISSUE #2266: Compatibility issue with Boost.Asio
Hi,

A few compatiblity issues with Boost.Asio have been introduced in commit 7335c6ccd492325bb54df4398c897403d6bea6b6.

Specifically, 

https://github.com/stephenberry/glaze/blame/8879dd5e634ff6ed0116e09d01074fb0e9bafa4a/include/glaze/net/http_server.hpp#L2027

and 

https://github.com/stephenberry/glaze/blame/8879dd5e634ff6ed0116e09d01074fb0e9bafa4a/include/glaze/net/http_server.hpp#L1519

I'll investigate why the current workflows didn't catch the errors but I'm guessing it has to do with the compilation flags.

The error is reproducible with a basic HTTP server example: https://godbolt.org/z/eWvvYWbvP

### PR DESCRIPTION
**Pull request by azais-corentin**
This fixes #2266.

## Summary

This PR fixes the `boost-asio.yml` workflow which was incorrectly using standalone Asio instead of Boost.Asio, and resolves compilation errors when building with Boost.Asio.

## Changes

CI workflow (`boost-asio.yml`):

- Disabled bundled standalone Asio (`-Dglaze_USE_BUNDLED_ASIO=OFF`)
- Added `Boost_ROOT` environment variable to properly locate Boost installation

Boost.Asio compatibility:

- **Error code types**: In Boost.Asio, `asio::error_code` is `boost::system::error_code` which is **not** implicitly convertible to `std::error_code`.
Changed async callback signatures to use `asio::error_code` consistently.
Use make_error_code(asio::error::eof) and make_error_code(asio::error::operation_aborted) for comparisons.
- **SSL includes**: Added conditional SSL header includes (`<asio/ssl.hpp>` or `<boost/asio/ssl.hpp>`) to `glaze_asio.hpp`
- **http_client.hpp**: Now includes `glaze_asio.hpp` instead of `<asio.hpp>` directly for proper abstraction

### CODE REVIEW

**Comment by azais-corentin** [comment]
I have found an approach that doesn't change the user facing API.
We can:
1. Add `std::is_error_code_enum` specializations for `boost::asio::error::basic_errors` and `boost::asio::error::misc_errors`
2. Create wrapper `std::error_category` instances for each Boost.Asio error category
3. Add `make_error_code` overloads in the `boost::asio::error` namespace for ADL

Doing this will allow user code to compare `std::error_code` with `asio::error::eof`, ...

**Comment by azais-corentin** [comment]
@stephenberry could you please review this?

**Comment by stephenberry** [comment]
The PR description mentions:

> I've added a `to_std_error_code` helper which can convert a `asio::error_code` to a `std::error_code`. There's also `is_eof_error` and `is_operation_aborted_error`.

However, these helpers don't appear in the actual diff. The implementation instead uses:
- `asio::error_code` consistently throughout the code
- `make_error_code(asio::error::eof)` and `make_error_code(asio::error::operation_aborted)` for comparisons

Could you update the PR description to reflect the actual changes? The current approach works fine, but the description is misleading.

**Comment by azais-corentin** [comment]
Indeed, that's a leftover from a previous attempt. I'll update.

**Comment by azais-corentin** [comment]
There, it's done.

**Comment by stephenberry** [comment]
@azais-corentin, thanks so much working this fix! It looks great! I'm merging it
