### ISSUE TITLE
Regression/build error on 32-bit Android with neon instructions

### ISSUE THREAD

**Issue by biodranik** [stephenberry/glaze#2330]
Regression was likely introduced in 85629bcca1e87668b21c7e670939053cd0e371a7

The build for armv7 fails with:

```
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/simd/neon.hpp:42:17: error: use of undeclared identifier 'vmaxvq_u8'
     42 |             if (vmaxvq_u8(any) == 0) {
        |                 ^
```

Looks like vmaxvq_u8 is available only on `__aarch64__` : https://github.com/wolfpld/etcpak/issues/25

https://github.com/organicmaps/organicmaps/actions/runs/22258784885/job/64393723684#step:8:1104
```
  FAILED: libs/platform/CMakeFiles/platform.dir/Unity/unity_0_cxx.cxx.o 
  /usr/bin/ccache /usr/bin/ccache /usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --sysroot=/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDEBUG -DJANSSON_USING_CMAKE -DUCONFIG_USE_LOCAL -DUSE_FILE32API -I/home/runner/work/organicmaps/organicmaps -I/home/runner/work/organicmaps/organicmaps/libs -I/home/runner/work/organicmaps/organicmaps/tools -I/home/runner/work/organicmaps/organicmaps/3party/utfcpp/source -I/home/runner/work/organicmaps/organicmaps/android/sdk/nativeOutputs/Debug/2vk5i64g/armeabi-v7a/3party/jansson/jansson/include -I/home/runner/work/organicmaps/organicmaps/3party/expat/expat/lib -I/home/runner/work/organicmaps/organicmaps/android/sdk/nativeOutputs/Debug/2vk5i64g/armeabi-v7a/3party/expat/expat -I/home/runner/work/organicmaps/organicmaps/3party/icu/. -I/home/runner/work/organicmaps/organicmaps/3party/icu/icu/icu4c/source/common -I/home/runner/work/organicmaps/organicmaps/3party/icu/icu/icu4c/source/i18n -isystem /home/runner/work/organicmaps/organicmaps/3party/boost -isystem /home/runner/work/organicmaps/organicmaps/3party/glaze/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -frtti -fno-limit-debug-info  -std=c++23 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -ffast-math -fno-omit-frame-pointer -Wall -Wextra -Wpedantic -Wno-unused-parameter -pthread -Wno-missing-braces -MD -MT libs/platform/CMakeFiles/platform.dir/Unity/unity_0_cxx.cxx.o -MF libs/platform/CMakeFiles/platform.dir/Unity/unity_0_cxx.cxx.o.d -o libs/platform/CMakeFiles/platform.dir/Unity/unity_0_cxx.cxx.o -c /home/runner/work/organicmaps/organicmaps/android/sdk/nativeOutputs/Debug/2vk5i64g/armeabi-v7a/libs/platform/CMakeFiles/platform.dir/Unity/unity_0_cxx.cxx
  In file included from /home/runner/work/organicmaps/organicmaps/android/sdk/nativeOutputs/Debug/2vk5i64g/armeabi-v7a/libs/platform/CMakeFiles/platform.dir/Unity/unity_0_cxx.cxx:64:
  In file included from /home/runner/work/organicmaps/organicmaps/libs/platform/products.cpp:11:
  In file included from /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json.hpp:11:
  In file included from /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/float_format.hpp:11:
  In file included from /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:13:
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/simd/neon.hpp:42:17: error: use of undeclared identifier 'vmaxvq_u8'
     42 |             if (vmaxvq_u8(any) == 0) {
        |                 ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/simd/neon.hpp:58:17: error: use of undeclared identifier 'vmaxvq_u8'
     58 |             if (vmaxvq_u8(check(v)) == 0) {
        |                 ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:945:27: note: in instantiation of function template specialization 'glz::detail::neon_string_escape<char, (lambda at /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:917:39) &>' requested here
    945 |                   detail::neon_string_escape(c, e, data, n, write_escape);
        |                           ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:48:53: note: in instantiation of function template specialization 'glz::to<10, std::string>::op<opts{10, true, false, true, true, false, false, false, false, 0}, std::string &, std::string &, glz::context &, unsigned int>' requested here
     48 |          to<JSON, std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
        |                                                     ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:1595:33: note: in instantiation of function template specialization 'glz::serialize<10>::op<opts{10, true, false, true, true, false, false, false, false, 0}, std::string &, glz::context &, std::string &, unsigned int &>' requested here
   1595 |                serialize<JSON>::op<write_unchecked_off<Opts>()>(*value, ctx, b, ix);
        |                                 ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:2209:51: note: in instantiation of function template specialization 'glz::to<10, std::optional<std::string>>::op<opts{10, true, false, true, true, false, false, false, false, 0}, std::optional<std::string> &, glz::context &, std::string &, unsigned int>' requested here
   2209 |                         to<JSON, val_t>::template op<check_opts>(get_member(value, get<I>(t)), ctx, b, ix);
        |                                                   ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:48:53: note: in instantiation of function template specialization 'glz::to<10, products::ProductsConfig>::op<opts{10, true, false, true, true, false, false, false, false, 0}, products::ProductsConfig &, std::string &, glz::context &, unsigned int>' requested here
     48 |          to<JSON, std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
        |                                                     ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:1595:33: note: in instantiation of function template specialization 'glz::serialize<10>::op<opts{10, true, false, true, true, false, false, false, false, 0}, products::ProductsConfig &, glz::context &, std::string &, unsigned int &>' requested here
   1595 |                serialize<JSON>::op<write_unchecked_off<Opts>()>(*value, ctx, b, ix);
        |                                 ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/core/write.hpp:28:57: note: in instantiation of function template specialization 'glz::to<10, std::optional<products::ProductsConfig>>::op<opts{10, true, false, true, true, false, false, false, false, 0}, std::optional<products::ProductsConfig> &, glz::context &, std::string &, unsigned int>' requested here
     28 |       to<Opts.format, std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), ctx, buffer, ix);
        |                                                         ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/core/write.hpp:80:14: note: in instantiation of function template specialization 'glz::write<opts{10, true, false, true, true, false, false, false, false, 0}, std::optional<products::ProductsConfig> &, std::string, glz::context &>' requested here
     80 |       return write<Opts>(std::forward<T>(value), buffer, ctx);
        |              ^
  /home/runner/work/organicmaps/organicmaps/3party/glaze/include/glaze/json/write.hpp:2630:23: note: in instantiation of function template specialization 'glz::write<opts{10, true, false, true, true, false, false, false, false, 0}, std::optional<products::ProductsConfig> &, std::string>' requested here
   2630 |       const auto ec = write<set_json<Opts>()>(std::forward<T>(value), buffer);
        |                       ^
  /home/runner/work/organicmaps/organicmaps/libs/platform/products.cpp:98:33: note: in instantiation of function template specialization 'glz::write_file_json<opts{10, true, false, true, true, false, false, false, false, 0}, std::optional<products::ProductsConfig> &, std::string>' requested here
     98 |     if (auto const error = glz::write_file_json(productsConfig, outFilePath, std::string{}); error)
        |                                 ^
  2 errors generated.
```

LLM-suggested workaround (untested!):
```
// AArch32 workaround for horizontal max of uint8x16_t
uint8_t hmax_u8_neon(uint8x16_t v) {
    uint8x8_t tmp = vpmax_u8(vget_low_u8(v), vget_high_u8(v));
    tmp = vpmax_u8(tmp, tmp);
    tmp = vpmax_u8(tmp, tmp);
    tmp = vpmax_u8(tmp, tmp);
    return vget_lane_u8(tmp, 0);
}
```

**Comment by stephenberry** [comment]
I'll look into this ASAP, but if you need a quick fix you can disable SIMD with the CMake option: `glaze_DISABLE_SIMD_WHEN_SUPPORTED ON`

**Comment by biodranik** [comment]
Err… we're including glaze headers directly, without adding a cmake dependency. Need to check which important config options may be missing/lead to issues…

**Comment by stephenberry** [comment]
I would like to not require CMake. So, I can look into using has_include for the Neon headers and that might fix this issue.

**Comment by stephenberry** [comment]
@biodranik, so AArch32 does have NEON support, but not `vmaxvq_u8`. We could fall back to SWAR, but I've implemented a simple patch in #2336 that avoids `vmaxvq_u8`. I think this should give a bit higher performance than SWAR.

I merged this fix with `main`, so could you check and see if this fixes your issue?

**Comment by biodranik** [comment]
@stephenberry thanks! It compiles on Android now. Let's beta-test your main :)
