### ISSUE TITLE
Enum string serialization/parsing using glz::meta + glz::enumerate fails for TOML

### ISSUE THREAD

**Issue by kowalczyk-jan** [stephenberry/glaze#2176]
Hi!

The following example fails to compile using v6.4.0:

```cpp
#include <glaze/json.hpp>
#include <glaze/toml.hpp>

#include <print>

enum class EnumTest { Enum1, Enum2 };

template <>
struct glz::meta<EnumTest> {
  using enum EnumTest;
  static constexpr auto value = glz::enumerate(Enum1, Enum2);
};

int main() {
  EnumTest    test;
  std::string buffer{R"("Enum2")"};

  auto ec = glz::read_toml(test, buffer);
  if (ec) {
    std::println("Error: {}", glz::format_error(ec, buffer));
  }
  else {
    std::println("TOML Success");
  }

  auto ec = glz::read_json(test, buffer);
  if (ec) {
    std::println("Error: {}", glz::format_error(ec, buffer));
  }
  else {
    std::println("JSON Success");
  }
}

```

It appears the meta specialization is not available for TOML even though it is for JSON. 

```
main.cpp: In function ‘int main()’:
main.cpp:18:27: error: no matching function for call to ‘read_toml(EnumTest&, std::string&)’
   18 |   auto ec = glz::read_toml(test, buffer);
      |             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from build/_deps/glaze-src/include/glaze/toml.hpp:8,
                 from main.cpp:2:
build/_deps/glaze-src/include/glaze/toml/read.hpp:1129:35: note: candidate: ‘template<class T, class Buffer>  requires (read_supported<T, 400>) && (is_buffer<Buffer>) glz::error_ctx glz::read_toml(T&, Buffer&&)’
 1129 |    [[nodiscard]] inline error_ctx read_toml(T& value, Buffer&& buffer)
      |                                   ^~~~~~~~~
build/_deps/glaze-src/include/glaze/toml/read.hpp:1129:35: note:   template argument deduction/substitution failed:
build/_deps/glaze-src/include/glaze/toml/read.hpp:1129:35: note: constraints not satisfied
In file included from build/_deps/glaze-src/include/glaze/core/as_array_wrapper.hpp:6,
                 from build/_deps/glaze-src/include/glaze/json.hpp:6,
                 from main.cpp:1:
build/_deps/glaze-src/include/glaze/core/opts.hpp: In substitution of ‘template<class T, class Buffer>  requires (read_supported<T, 400>) && (is_buffer<Buffer>) glz::error_ctx glz::read_toml(T&, Buffer&&) [with T = EnumTest; Buffer = std::__cxx11::basic_string<char>&]’:
main.cpp:18:27:   required from here
   18 |   auto ec = glz::read_toml(test, buffer);
      |             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
build/_deps/glaze-src/include/glaze/core/opts.hpp:762:12:   required for the satisfaction of ‘read_supported<T, 400>’ [with T = EnumTest]
build/_deps/glaze-src/include/glaze/core/opts.hpp:762:29:   in requirements  [with Format = 400; T = EnumTest]
build/_deps/glaze-src/include/glaze/core/opts.hpp:762:40: note: the required expression ‘glz::from<Format, typename std::remove_cvref<_Tp>::type>{}’ is invalid
  762 |    concept read_supported = requires { from<Format, std::remove_cvref_t<T>>{}; };
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: note: set ‘-fconcepts-diagnostics-depth=’ to at least 2 for more detail
build/_deps/glaze-src/include/glaze/toml/read.hpp:1136:48: note: candidate: ‘template<class T, class Buffer>  requires (read_supported<T, 400>) && (is_buffer<Buffer>) glz::expected<T, glz::error_ctx> glz::read_toml(Buffer&&)’
 1136 |    [[nodiscard]] inline expected<T, error_ctx> read_toml(Buffer&& buffer)
      |                                                ^~~~~~~~~
build/_deps/glaze-src/include/glaze/toml/read.hpp:1136:48: note:   candidate expects 1 argument, 2 provided
```

The documentation states:

> The same compile-time reflection metadata you already use for JSON works for TOML, so you can reuse your glz::meta specializations without additional boilerplate.

.. so am I correct in assuming this should work for both?

 — Jan

**Comment by stephenberry** [comment]
Thanks for pointing this out! TOML support was missing the same enum handling as you noted. TOML has the most minimal implementation in Glaze right now, but please report limitations and issues as you encounter them. And, support will continue to mature.

Fixed in #2181
